<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> __cxa_vec_new2 and deallocation functions that throw exceptions
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:cxx-abi-dev%40codesourcery.com?Subject=Re%3A%20__cxa_vec_new2%20and%20deallocation%20functions%20that%20throw%20exceptions&In-Reply-To=%3C1052937445.1498.35.camel%40doubledemon.codesourcery.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="001712.html">
   <LINK REL="Next"  HREF="001707.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>__cxa_vec_new2 and deallocation functions that throw exceptions</H1>
    <B>Mark Mitchell</B> 
    <A HREF="mailto:cxx-abi-dev%40codesourcery.com?Subject=Re%3A%20__cxa_vec_new2%20and%20deallocation%20functions%20that%20throw%20exceptions&In-Reply-To=%3C1052937445.1498.35.camel%40doubledemon.codesourcery.com%3E"
       TITLE="__cxa_vec_new2 and deallocation functions that throw exceptions">mark at codesourcery.com
       </A><BR>
    <I>Wed May 14 18:37:25 UTC 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="001712.html">[cxx-abi-dev] Long bitfields in PODs
</A></li>
        <LI>Next message: <A HREF="001707.html">[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that throw exceptions
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1706">[ date ]</a>
              <a href="thread.html#1706">[ thread ]</a>
              <a href="subject.html#1706">[ subject ]</a>
              <a href="author.html#1706">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>The ABI says that, for __cxa_vec_new2 and __cxa_vec_new3:

  If dealloc throws an exception, the result is undefined.

I don't understand this restriction.  In particular, the ISO C++
standard says (if I read it correctly) that:

  struct S {
    S() { throw 1; }
    void* operator new[] (size_t s) { return ::operator new[] (s); }
    void operator delete[] (void*) { throw 2; }
  };

  new S[5];

results in a call to std::terminate.  (First, the array is allocated,
then the elements are constructed, but the first one throws an
exception, which causes the deallocation function to be called, which
throws an exception, so terminate is called.)

Shouldn't __cxa_vec_new[23] be required to call std::terminate if
dealloc throws an exception?

-- 
Mark Mitchell
CodeSourcery, LLC
<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/cxx-abi-dev">mark at codesourcery.com</A>


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="001712.html">[cxx-abi-dev] Long bitfields in PODs
</A></li>
	<LI>Next message: <A HREF="001707.html">[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that throw exceptions
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1706">[ date ]</a>
              <a href="thread.html#1706">[ thread ]</a>
              <a href="subject.html#1706">[ subject ]</a>
              <a href="author.html#1706">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/cxx-abi-dev">More information about the cxx-abi-dev
mailing list</a><br>
</body></html>
