<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [cxx-abi-dev] How to detect a forced unwind in a catch block?
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:cxx-abi-dev%40codesourcery.com?Subject=Re%3A%20%5Bcxx-abi-dev%5D%20How%20to%20detect%20a%20forced%20unwind%20in%20a%20catch%20block%3F&In-Reply-To=%3CCAGL0aWceAhdtkGgcASGf4X-G_ds9uVEyg%2BBZd4Rd4ckUGfB%2B%2Bw%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="002961.html">
   <LINK REL="Next"  HREF="002963.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[cxx-abi-dev] How to detect a forced unwind in a catch block?</H1>
    <B>Richard Smith</B> 
    <A HREF="mailto:cxx-abi-dev%40codesourcery.com?Subject=Re%3A%20%5Bcxx-abi-dev%5D%20How%20to%20detect%20a%20forced%20unwind%20in%20a%20catch%20block%3F&In-Reply-To=%3CCAGL0aWceAhdtkGgcASGf4X-G_ds9uVEyg%2BBZd4Rd4ckUGfB%2B%2Bw%40mail.gmail.com%3E"
       TITLE="[cxx-abi-dev] How to detect a forced unwind in a catch block?">richardsmith at googlers.com
       </A><BR>
    <I>Tue Sep  6 19:39:10 UTC 2016</I>
    <P><UL>
        <LI>Previous message: <A HREF="002961.html">[cxx-abi-dev] How to detect a forced unwind in a catch block?
</A></li>
        <LI>Next message: <A HREF="002963.html">[cxx-abi-dev] How to detect a forced unwind in a catch block?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2962">[ date ]</a>
              <a href="thread.html#2962">[ thread ]</a>
              <a href="subject.html#2962">[ subject ]</a>
              <a href="author.html#2962">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On 6 September 2016 at 11:56, John McCall &lt;<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/cxx-abi-dev">rjmccall at apple.com</A>&gt; wrote:

&gt;<i> &gt; On Sep 6, 2016, at 11:50 AM, Thiago Macieira &lt;<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/cxx-abi-dev">thiago at kde.org</A>&gt; wrote:
</I>&gt;<i> &gt; Em ter&#231;a-feira, 6 de setembro de 2016, &#224;s 11:38:43 PDT, John McCall
</I>&gt;<i> escreveu:
</I>&gt;<i> &gt;&gt; This would be inappropriate; the appropriate solution would be to ask
</I>&gt;<i> the
</I>&gt;<i> &gt;&gt; committee for a new function in namespace std that could be implemented
</I>&gt;<i> &gt;&gt; with abi::__forced_unwind.  I believe that's the chief purpose of that
</I>&gt;<i> &gt;&gt; function, to allow that sort of functionality to be implemented in the
</I>&gt;<i> &gt;&gt; future.
</I>&gt;<i> &gt;&gt;
</I>&gt;<i> &gt;&gt; If std::current_exception works, of course, all the better.
</I>&gt;<i> &gt;
</I>&gt;<i> &gt; I will post to std-discussion and see if there's a consensus. I'm not
</I>&gt;<i> sure
</I>&gt;<i> &gt; there can be because this is outside of the C++ language: there's no such
</I>&gt;<i> &gt; thing as forced unwinds in the standard.
</I>&gt;<i>
</I>&gt;<i> Hmm.  I think this used to not be true; there were library features (e.g.
</I>&gt;<i> longjmp)
</I>&gt;<i> that were allowed, but not required, to be implemented by unwinding the
</I>&gt;<i> stack.
</I>&gt;<i> But now it seems that these places have all been changed to specify
</I>&gt;<i> undefined
</I>&gt;<i> behavior if they would bypass any non-trivial destructors.
</I>&gt;<i>
</I>
That's true, but it does not place restrictions on intervening 'catch
(...)' blocks, and (since no exception has been thrown) they presumably
must /not/ be entered. (You don't get UB from a longjmp where a
corresponding throw would enter a catch(...) block -- although that may
just be a wording defect.)

The possibility of forced unwinding invoking a 'catch (...)' block with no
current exception seems broken to me. For instance, this may or may not
call terminate() if f() results in a forced unwind, depending on how
'throw;' is implemented:

  try {
    f();
  } catch (...) {
    log_error(); // might reasonably assert(std::current_exception())
    throw;
  }

Pretending that a forced unwind throws a C++ exception of some known type
seems likely to be the best approach -- and I'd expect that exception to be
capturable via std::current_exception and counted by
std::uncaught_exceptions, or exception-safe code using those facilities
will not function correctly in the presence of a forced unwind. (And
likewise for foreign exceptions; we presumably want to pretend that they
are just like C++ exceptions but are of a type that doesn't match that of
any handlers.)
-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="http://sourcerytools.com/pipermail/cxx-abi-dev/attachments/20160906/b24b9365/attachment-0001.html">http://sourcerytools.com/pipermail/cxx-abi-dev/attachments/20160906/b24b9365/attachment-0001.html</A>&gt;
</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="002961.html">[cxx-abi-dev] How to detect a forced unwind in a catch block?
</A></li>
	<LI>Next message: <A HREF="002963.html">[cxx-abi-dev] How to detect a forced unwind in a catch block?
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2962">[ date ]</a>
              <a href="thread.html#2962">[ thread ]</a>
              <a href="subject.html#2962">[ subject ]</a>
              <a href="author.html#2962">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/cxx-abi-dev">More information about the cxx-abi-dev
mailing list</a><br>
</body></html>
